import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import crypto from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const safeName = /^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/;
export type MarketplaceSummary = { id: string; name: string; display_name: string; source: string; kind: "default" | "git" | "local"; root_path: string; ref: string; sparse_paths: string[]; plugin_count: number; updated_at: string; removable: boolean; updatable: boolean };
export type MarketplacePluginSummary = { id: string; marketplace_id: string; marketplace_name: string; name: string; display_name: string; description: string; version: string; category: string; publisher: string; installation: string; authentication: string; installed: boolean; installed_plugin_id?: string | null; source_path?: string; source_type: "local" | "url" | "git-subdir"; source_url?: string; source_ref?: string; source_sha?: string; relative_path?: string };
type Entry = { id: string; kind: "git" | "local"; source: string; git_url?: string; cache_path?: string; ref?: string; sparse_paths?: string[]; updated_at?: string };

const now = () => new Date().toISOString();
const rootConfig = () => path.join(os.homedir(), ".sztu");
const inside = (root: string, value: string) => { if (!value.startsWith("./")) throw new Error("marketplace plugin paths must start with ./"); const target = path.resolve(root, value.slice(2)); const base = path.resolve(root); if (target !== base && !target.startsWith(`${base}${path.sep}`)) throw new Error("marketplace plugin path escapes its root"); return target; };
const git = async (args: string[], timeout = 180000) => { try { await execFileAsync("git", args, { timeout, maxBuffer: 2 * 1024 * 1024 }); } catch (e) { const error = e as { stderr?: string; message?: string }; throw new Error((error.stderr || error.message || "Git command failed").trim().slice(-1200)); } };
const readJson = async (file: string): Promise<any> => JSON.parse(await readFile(file, "utf8"));
const normalizeSparse = (value: string): string => { const normalized = value.trim().replaceAll("\\", "/").replace(/^\.\//, "").replace(/\/+$/, ""); if (!normalized || normalized.startsWith("/") || normalized.split("/").includes("..")) throw new Error(`invalid sparse path: ${value}`); return normalized; };

export class MarketplaceManager {
  private readonly configRoot = rootConfig(); private readonly configFile = path.join(this.configRoot, "plugin-marketplaces.json"); private readonly cacheRoot = path.join(this.configRoot, "marketplaces");
  constructor(private readonly projectRoot = process.cwd()) {}
  private async entries(): Promise<Entry[]> { try { const data = await readJson(this.configFile); return Array.isArray(data?.marketplaces) ? data.marketplaces.filter((x: any) => x && typeof x.id === "string") : []; } catch { return []; } }
  private async save(entries: Entry[]) { await mkdir(this.configRoot, { recursive: true }); const tmp = `${this.configFile}.tmp`; await writeFile(tmp, `${JSON.stringify({ marketplaces: entries }, null, 2)}\n`, "utf8"); const { rename } = await import("node:fs/promises"); await rename(tmp, this.configFile); }
  private manifest(root: string): string { const candidates = [path.join(root, "marketplace.json"), path.join(root, ".agents", "plugins", "marketplace.json"), path.join(root, ".claude-plugin", "marketplace.json")]; const found = candidates.find((p) => { try { return requireFs(p); } catch { return false; } }); if (!found) throw new Error("marketplace.json was not found in this source"); return found; }
  private async summary(id: string, root: string, source: string, kind: "default" | "git" | "local", ref = "", sparse: string[] = [], updated_at = "", removable = false, updatable = false): Promise<MarketplaceSummary> { const file = this.manifest(root); const data = await readJson(file); const name = String(data.name || path.basename(root)); const iface = data.interface && typeof data.interface === "object" ? data.interface : {}; return { id, name, display_name: String(iface.displayName || name), source, kind, root_path: root, ref, sparse_paths: sparse, plugin_count: Array.isArray(data.plugins) ? data.plugins.length : 0, updated_at, removable, updatable }; }
  async list(): Promise<{ marketplaces: MarketplaceSummary[]; plugins: MarketplacePluginSummary[] }> {
    const marketplaces: MarketplaceSummary[] = []; const seen = new Set<string>();
    const defaults = [[this.projectRoot, path.join(this.projectRoot, ".agents", "plugins", "marketplace.json"), "workspace"], [this.projectRoot, path.join(this.projectRoot, ".claude-plugin", "marketplace.json"), "workspace-legacy"], [path.join(os.homedir(), ".agents"), path.join(os.homedir(), ".agents", "plugins", "marketplace.json"), "personal"]] as const;
    for (const [root, file, label] of defaults) { try { if (requireFs(file) && !seen.has(file)) { seen.add(file); marketplaces.push(await this.summary(`default:${label}`, root, file, "default")); } } catch {} }
    for (const e of await this.entries()) { try { const root = path.resolve(e.kind === "git" ? String(e.cache_path) : e.source); const s = await this.summary(e.id, root, e.source, e.kind, e.ref || "", e.sparse_paths || [], e.updated_at || "", true, e.kind === "git"); marketplaces.push(s); } catch {} }
    const plugins: MarketplacePluginSummary[] = []; for (const m of marketplaces) { try { const data = await readJson(this.manifest(m.root_path)); for (const item of Array.isArray(data.plugins) ? data.plugins : []) { if (!item || !safeName.test(String(item.name || ""))) continue; const raw = item.source; const source = typeof raw === "string" ? { source: "local", path: raw } : raw && typeof raw === "object" ? raw : null; if (!source) continue; const sourceType = String(source.source || "local") as "local" | "url" | "git-subdir"; const relativePath = String(source.path || ""); let sourcePath: string | undefined; if (sourceType === "local" || (!source.url && relativePath)) { try { sourcePath = inside(m.root_path, relativePath); } catch { continue; } } else if (!["url", "git-subdir"].includes(sourceType) || !source.url) continue; const iface = item.interface && typeof item.interface === "object" ? item.interface : {}; plugins.push({ id: `${m.id}:${item.name}`, marketplace_id: m.id, marketplace_name: m.display_name, name: String(item.name), display_name: String(iface.displayName || item.display_name || item.name), description: String(item.description || ""), version: String(item.version || "local"), category: String(item.category || "Other"), publisher: typeof item.publisher === "object" ? String(item.publisher.name || "") : String(item.publisher || ""), installation: String(item.policy?.installation || "AVAILABLE"), authentication: String(item.policy?.authentication || "ON_INSTALL"), installed: false, installed_plugin_id: null, source_path: sourcePath, source_type: sourceType, source_url: source.url ? String(source.url) : undefined, source_ref: source.ref ? String(source.ref) : undefined, source_sha: source.sha ? String(source.sha) : undefined, relative_path: relativePath }); } } catch {} } return { marketplaces, plugins };
  }
  async add(source: string, ref = "", sparse: string[] = []): Promise<MarketplaceSummary> { const local = path.resolve(source); const entries = await this.entries(); if (requireFs(local)) { const id = `configured:${crypto.createHash("sha256").update(`local:${local}`).digest("hex").slice(0, 16)}`; if (entries.some((e) => e.id === id)) throw new Error("marketplace source is already configured"); this.manifest(local); const entry: Entry = { id, kind: "local", source: local, updated_at: now() }; await this.save([...entries, entry]); return this.summary(id, local, local, "local", "", [], entry.updated_at, true, false); } const shorthand = /^([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+?)(?:@([^\s]+))?$/.exec(source); const url = shorthand ? `https://github.com/${shorthand[1]}/${shorthand[2].replace(/\.git$/, "")}.git` : source; if (!/^https?:\/\/|^ssh:\/\//.test(url) || /[?#]/.test(url) || /:\/\/[^/]*@/.test(url)) throw new Error("marketplace source must be a safe Git URL or owner/repo"); const selected = ref || shorthand?.[3] || ""; const id = `configured:${crypto.createHash("sha256").update(`git:${url}:${selected}:${sparse.join(",")}`).digest("hex").slice(0, 16)}`; if (entries.some((e) => e.id === id)) throw new Error("marketplace source is already configured"); const destination = path.join(this.cacheRoot, `${path.basename(url, ".git")}-${id.slice(-12)}`); await mkdir(this.cacheRoot, { recursive: true }); await git(["clone", "--filter=blob:none", "--no-tags", "--depth", "1", url, destination]); if (selected) { await git(["-C", destination, "fetch", "--depth", "1", "origin", selected]); await git(["-C", destination, "checkout", "--detach", "FETCH_HEAD"]); } this.manifest(destination); const entry: Entry = { id, kind: "git", source, git_url: url, cache_path: destination, ref: selected, sparse_paths: sparse, updated_at: now() }; await this.save([...entries, entry]); return this.summary(id, destination, source, "git", selected, sparse, entry.updated_at, true, true); }
  async refresh(id?: string): Promise<MarketplaceSummary[]> { const entries = await this.entries(); for (const e of entries.filter((x) => x.kind === "git" && (!id || x.id === id))) { const root = path.resolve(String(e.cache_path)); if (!root.startsWith(path.resolve(this.cacheRoot) + path.sep)) throw new Error("refusing to modify a path outside the marketplace cache"); await git(["-C", root, ...(e.ref ? ["fetch", "--depth", "1", "origin", e.ref] : ["pull", "--ff-only"])]); if (e.ref) await git(["-C", root, "checkout", "--detach", "FETCH_HEAD"]); e.updated_at = now(); } await this.save(entries); return (await this.list()).marketplaces; }
  async remove(id: string) { const entries = await this.entries(); const target = entries.find((e) => e.id === id); if (!target) throw new Error(`configured marketplace not found: ${id}`); if (target.kind === "git" && target.cache_path) { const root = path.resolve(target.cache_path); if (!root.startsWith(path.resolve(this.cacheRoot) + path.sep)) throw new Error("refusing to remove path outside marketplace cache"); await rm(root, { recursive: true, force: true }); } await this.save(entries.filter((e) => e.id !== id)); }
  async materialize(id: string): Promise<{ path: string; temporary_root?: string }> {
    const item = (await this.list()).plugins.find((p) => p.id === id); if (!item) throw new Error("marketplace plugin not found");
    if (item.source_path) return { path: item.source_path };
    if (!item.source_url) throw new Error(`marketplace plugin source is not installable: ${item.name}`);
    const temporary = path.join(this.cacheRoot, ".tmp", `plugin-${crypto.randomUUID()}`); await mkdir(path.dirname(temporary), { recursive: true });
    try {
      const cloneArgs = ["clone", "--filter=blob:none", "--no-tags", ...(item.source_sha ? [] : ["--depth", "1"]), item.source_url, temporary]; await git(cloneArgs);
      const revision = item.source_sha || item.source_ref || ""; if (revision) { await git(["-C", temporary, "fetch", "--depth", "1", "origin", revision]); await git(["-C", temporary, "checkout", "--detach", "FETCH_HEAD"]); }
      if (item.relative_path) { const sparse = normalizeSparse(item.relative_path); await git(["-C", temporary, "sparse-checkout", "set", "--no-cone", sparse]); }
      const pluginPath = item.relative_path ? inside(temporary, `./${normalizeSparse(item.relative_path)}`) : temporary;
      return { path: pluginPath, temporary_root: temporary };
    } catch (error) { await rm(temporary, { recursive: true, force: true }); throw error; }
  }
  async cleanupMaterialized(temporaryRoot?: string): Promise<void> { if (!temporaryRoot) return; const root = path.resolve(temporaryRoot); const cache = path.resolve(path.join(this.cacheRoot, ".tmp")); if (root !== cache && !root.startsWith(`${cache}${path.sep}`)) throw new Error("refusing to remove path outside marketplace temporary cache"); await rm(root, { recursive: true, force: true }); }
}
const requireFs = (file: string) => { try { return existsSync(file) && (statSync(file).isDirectory() || statSync(file).isFile()); } catch { return false; } };
