import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { RuntimeSettings, SettingsStore } from "./settings.js";

export type ModelProfile = RuntimeSettings & { id: string; name: string; vendor: string; has_api_key: boolean; is_current: boolean; builtin: boolean };
type StoredProfile = ModelProfile & { api_key?: string };
export class ModelProfileStore {
  private profiles: StoredProfile[] = []; private loaded = false;
  constructor(private readonly settings: SettingsStore, private readonly filePath = path.join(process.env.SZTU_DATA_DIR ?? path.join(process.env.USERPROFILE ?? process.cwd(), ".sztu"), "model-profiles.json")) {}
  async list(): Promise<ModelProfile[]> { await this.load(); const current = await this.settings.get(); return this.profiles.map(({ api_key: _secret, ...profile }) => ({ ...profile, is_current: profile.model === current.model && profile.provider === current.provider && profile.base_url === current.base_url })); }
  async save(input: Partial<StoredProfile> & { name: string; vendor: string; provider: "anthropic" | "openai"; model: string; base_url: string; select?: boolean }): Promise<{ settings: RuntimeSettings; models: ModelProfile[] }> { await this.load(); const id = input.id || randomUUID(); let profile = this.profiles.find((item) => item.id === id); if (!profile) { profile = { id, name: input.name, vendor: input.vendor, provider: input.provider, model: input.model, base_url: input.base_url, has_api_key: false, is_current: false, builtin: false, api_format: input.provider === "anthropic" ? "anthropic_messages" : "openai_chat_completions", permission_mode: "normal", context_window: 128_000, max_output_tokens: 8192, temperature: null, top_p: null, reasoning_effort: "", timeout_s: 120, max_retries: 2, cache_control: true }; this.profiles.push(profile); } Object.assign(profile, input, { id, has_api_key: Boolean(input.api_key || profile.api_key) }); await this.persist(); const settings = input.select === false ? await this.settings.get() : await this.select(id); return { settings, models: await this.list() }; }
  async select(id: string): Promise<RuntimeSettings> { await this.load(); const profile = this.profiles.find((item) => item.id === id); if (!profile) throw new Error(`Unknown model profile: ${id}`); return this.settings.update({ provider: profile.provider, api_format: profile.api_format, model: profile.model, base_url: profile.base_url, context_window: profile.context_window, max_output_tokens: profile.max_output_tokens, temperature: profile.temperature, top_p: profile.top_p, reasoning_effort: profile.reasoning_effort, timeout_s: profile.timeout_s, max_retries: profile.max_retries, cache_control: profile.cache_control, ...(profile.api_key ? { api_key: profile.api_key } : {}) }); }
  async delete(id: string): Promise<ModelProfile[]> { await this.load(); const profile = this.profiles.find((item) => item.id === id); if (profile?.builtin) throw new Error("builtin profiles cannot be deleted"); this.profiles = this.profiles.filter((item) => item.id !== id); await this.persist(); return this.list(); }
  private async load(): Promise<void> { if (this.loaded) return; this.loaded = true; try { this.profiles = JSON.parse(await readFile(this.filePath, "utf8")) as StoredProfile[]; } catch { this.profiles = []; } }
  private async persist(): Promise<void> { await mkdir(path.dirname(this.filePath), { recursive: true }); await writeFile(this.filePath, `${JSON.stringify(this.profiles, null, 2)}\n`, "utf8"); }
}
