import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

export type PluginScope = "personal" | "workspace";
export type PluginSummary = { id: string; name: string; description: string; version: string; source: PluginScope; path: string; skills: string[]; installed: boolean; display_name: string; brand_color: string | null; enabled: boolean };

type Manifest = { name?: string; description?: string; version?: string; skills?: string | string[]; interface?: { displayName?: string; brandColor?: string } };

export class PluginManager {
  constructor(private readonly projectRoot: string, private readonly configRoot = path.join(process.env.USERPROFILE ?? process.cwd(), ".sztu")) {}
  private parent(scope: PluginScope): string { return scope === "personal" ? path.join(this.configRoot, "plugins") : path.join(this.projectRoot, ".sztu", "plugins"); }
  async list(): Promise<PluginSummary[]> { const enabled = await this.enabledOverrides(); const output: PluginSummary[] = []; for (const scope of ["personal", "workspace"] as const) { const parent = this.parent(scope); try { for (const entry of await readdir(parent, { withFileTypes: true })) { if (!entry.isDirectory()) continue; const root = path.join(parent, entry.name); const manifest = await this.readManifest(root); if (!manifest) continue; const name = manifest.name || entry.name; const id = `${scope}:${name}`; const skillDirs = Array.isArray(manifest.skills) ? manifest.skills : [manifest.skills ?? "skills"]; const skills: string[] = []; for (const directory of skillDirs) { try { for (const item of await readdir(path.resolve(root, directory), { withFileTypes: true })) if (item.isDirectory()) skills.push(item.name); } catch { /* optional skills */ } } output.push({ id, name, description: manifest.description ?? "", version: manifest.version ?? "", source: scope, path: root, skills: skills.sort(), installed: true, display_name: manifest.interface?.displayName ?? name, brand_color: /^#[0-9a-f]{6}$/i.test(manifest.interface?.brandColor ?? "") ? manifest.interface!.brandColor! : null, enabled: enabled[id] ?? true }); } } catch { /* optional root */ } } return output; }
  async install(sourcePath: string, scope: PluginScope): Promise<PluginSummary> { const source = path.resolve(sourcePath); if (!(await stat(source)).isDirectory()) throw new Error("plugin source must be a directory"); const manifest = await this.readManifest(source); if (!manifest) throw new Error("plugin.json or .codex-plugin/plugin.json is required"); const name = manifest.name || path.basename(source); if (!/^[A-Za-z0-9_.-]+$/.test(name)) throw new Error("invalid plugin name"); const destination = path.join(this.parent(scope), name); await mkdir(path.dirname(destination), { recursive: true }); await rm(destination, { recursive: true, force: true }); await cp(source, destination, { recursive: true }); const plugin = (await this.list()).find((item) => item.id === `${scope}:${name}`); if (!plugin) throw new Error("installed plugin could not be loaded"); return plugin; }
  async setEnabled(id: string, enabled: boolean): Promise<PluginSummary> { const plugin = (await this.list()).find((item) => item.id === id); if (!plugin) throw new Error(`Unknown plugin: ${id}`); const values = await this.enabledOverrides(); values[id] = enabled; await mkdir(this.configRoot, { recursive: true }); await writeFile(path.join(this.configRoot, "plugin-settings.json"), `${JSON.stringify({ plugins: values }, null, 2)}\n`, "utf8"); return { ...plugin, enabled }; }
  async uninstall(id: string): Promise<void> { const plugin = (await this.list()).find((item) => item.id === id); if (!plugin) throw new Error(`Unknown plugin: ${id}`); await rm(plugin.path, { recursive: true, force: true }); }
  async skillRoots(): Promise<Array<{ root: string; source: string; scope: "personal" | "workspace" }>> { const result: Array<{ root: string; source: string; scope: "personal" | "workspace" }> = []; for (const plugin of await this.list()) { if (!plugin.enabled) continue; const manifest = await this.readManifest(plugin.path); const directories = Array.isArray(manifest?.skills) ? manifest!.skills : [manifest?.skills ?? "skills"]; for (const directory of directories) { const root = path.resolve(plugin.path, directory); const relative = path.relative(plugin.path, root); if (!relative.startsWith("..") && !path.isAbsolute(relative)) result.push({ root, source: `${plugin.source === "personal" ? "user" : "project"}-plugin:${plugin.name}`, scope: plugin.source }); } } return result; }
  private async readManifest(root: string): Promise<Manifest | null> { for (const candidate of [path.join(root, ".codex-plugin", "plugin.json"), path.join(root, "plugin.json")]) { try { return JSON.parse(await readFile(candidate, "utf8")) as Manifest; } catch { /* next */ } } return null; }
  private async enabledOverrides(): Promise<Record<string, boolean>> { try { return (JSON.parse(await readFile(path.join(this.configRoot, "plugin-settings.json"), "utf8")) as { plugins?: Record<string, boolean> }).plugins ?? {}; } catch { return {}; } }
}
