import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

const root = path.resolve(import.meta.dirname, "..");
const protocolSource = path.join(root, "packages", "protocol", "src", "index.ts");
const serverSource = path.join(root, "packages", "runtime-ts", "src", "server.ts");
const output = path.join(root, "docs", "reference", "wire-protocol.md");

function typeSection(node: ts.InterfaceDeclaration, source: ts.SourceFile): string {
  const rows = node.members.filter(ts.isPropertySignature).map((field) => {
    const name = field.name.getText(source);
    const type = (field.type?.getText(source) ?? "unknown").replace(/\s+/g, " ").replaceAll("|", "\\|");
    return `| \`${name}\` | \`${type}\` | ${field.questionToken ? "no" : "yes"} |`;
  });
  const name = node.name.text;
  return `### ${name}\n\n| Field | Type | Required |\n| --- | --- | --- |\n${rows.join("\n")}\n`;
}

const protocol = await readFile(protocolSource, "utf8");
const server = await readFile(serverSource, "utf8");
const source = ts.createSourceFile(protocolSource, protocol, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
const interfaces = source.statements.filter(ts.isInterfaceDeclaration);
const methods = [...server.matchAll(/case\s+"([^"]+)"/g)].map((match) => match[1]).filter((method, index, all) => all.indexOf(method) === index).sort();
const document = [
  "# Wire Protocol\n",
  "> Generated by `scripts/gen_protocol_doc.ts` from `packages/protocol/src/index.ts` and `packages/runtime-ts/src/server.ts`. **Do not edit manually.**\n",
  "[Back to documentation index](../README.md)\n",
  "## Transport\n",
  "- TCP loopback `127.0.0.1:7438` (override via `SZTU_HOST` / `SZTU_PORT`)\n- Each message is one `\\n`-terminated JSON line (NDJSON)\n- Commands use JSON-RPC 2.0; server events use `kind=event`.\n",
  "## Registered Methods\n",
  methods.map((method) => `- \`${method}\``).join("\n") + "\n",
  "## Shared Request and Result Types\n",
  interfaces.filter((node) => !node.name.text.endsWith("Event") && !node.name.text.startsWith("JsonRpc") && node.name.text !== "EventEnvelope").map((node) => typeSection(node, source)).join("\n"),
  "## Runtime Events\n",
  interfaces.filter((node) => node.name.text.endsWith("Event")).map((node) => typeSection(node, source)).join("\n"),
].join("\n");
await writeFile(output, `${document.trim()}\n`, "utf8");
console.log(`generated=${path.relative(root, output)}`);
